parameters:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build the project'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration ${{ parameter.buildConfiguration}}'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project'
  inputs:
    command: "publish"
    projects: "**/*.csproj"
    publishWebProjects: false
    arguments: '--no-build --configuration ${{ parameter.buildConfiguration}} --output $(Build.ArtifactStagingDirectory)/${{ parameter.buildConfiguration}}'
    zipAfterPublish: true
